### ISSUE TITLE
Missing Class in devtools

### ISSUE THREAD

**Issue by tundeajibawo** [swooletw/hyperf-packages#33]
The devtool in this package is missing a class. While trying to setup laravel-hyperf and installing with composer I got this error: 

`Fatal error: Uncaught Error: Class "Hyperf\Devtool\Generator\GeneratorCommand" not found in /opt/www/vendor/swooletw/hyperf-packages/src/devtool/src/Generator/ProviderCommand.php:9. 
`

I have compared with the devtool from this repository: https://github.com/hyperf/devtool and noticed the class is missing indeed. I have fixed on my machine by using the devtool from that repo instead and everything seems fine.

**Comment by albertcht** [comment]
Hi @tundeajibawo ,

Thanks for your report. I guess you install laravel-hyperf with `--no-dev` parameter.
I will fix it very soon.

**Comment by albertcht** [comment]
Hi @tundeajibawo ,

I've pushed the fix, you can try again.
